version: '3.4'

services:
  transavia.web.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development   
      - TransaviaApiUrl=http://transavia.api/api/
    ports:
      - "8888:80"    
    depends_on:
      - transavia.api
      
  transavia.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__TransaviaConnectionString=Server=sql;Database=TransaviaDB;User Id=sa;Password=123asdQ!     
      - RedisHost=redis.cache
      - RedisPort=6379
    ports:
      - "7777:80"
    depends_on:
      - sql
      - redis.cache
      - cache.web
      
  sql:
    image: microsoft/mssql-server-linux:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123asdQ!
    ports:
      - "5433:1433"

  redis.cache:
    image: redis
    ports:
      - "9999:6379"

  cache.web:    
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOST=redis.cache
    ports:
      - "8081:8081"    